

name: 'artifacts cleanup'
on: [workflow_dispatch]

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 0days # Set this to 0 to delete all artifacts
